.gitlab-ci.yml, .rootlogon.C, Snakefile, benchmarks/barrel_ecal/Snakefile, benchmarks/barrel_ecal/config.yml, benchmarks/barrel_ecal/scripts/emcal_barrel_particles_analysis.cxx, benchmarks/barrel_ecal/scripts/emcal_barrel_pi0_analysis.cxx, benchmarks/barrel_ecal/scripts/emcal_barrel_pion_rejection_analysis.cxx, flake.lock, flake.nix
This is https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/merge_requests/156, now contributed on GitHub
No
No
=> benchmarks/barrel_ecal: orchestrate using a Snakefile

.gitlab-ci.yml, Snakefile, benchmarks/zdc_lyso/README.md, benchmarks/zdc_lyso/Snakefile, benchmarks/zdc_lyso/analysis/analysis.py, benchmarks/zdc_lyso/config.yml, benchmarks/zdc_lyso/gen_particles.cxx
This benchmark studies acceptance and reconstruction for low-energy photons in the LYSO ZDC detector. Work performed by @JiaJunHuang120000.
- [x ] New feature (issue #__)
No.
Adds new benchmark.
=> Benchmark for low-energy photons in the ZDC LYSO

benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/doCompare_truth_real_widebins_dcaT.C, benchmarks/tracking_performances/doCompare_truth_real_widebins_dcaz.C, benchmarks/tracking_performances/doCompare_truth_real_widebins_mom.C
The PR consists of minor changes, I added the option to insert the software version which can be passed as the string in the code so that the plot also contains the software version.  I also stored the numbers in the text file which can be used for comparison in different versions. This is just for further information. If we can also add DCAT resolution to the snake file then it will be good to show in the collaboration meeting both momentum and DCAT resolution for the latest tagged ePIC software.
- [x ] Other: __
- Option to add software version which is important for the plots (access them using command and pass it as the string). I also stored the numbers in a text file with all the information that can be used for the validation.
- [ x] Changes have been communicated to collaborators …
=> included software version

benchmarks/zdc_lyso/analysis/analysis.py
A modified analysis code for zdc lyso single photon analysis. Changed some plots previously present and added some other plots.
No.
No.
=> Modified zdc lyso analysis code.

benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/Tracking_Performances.C
Should we go ahead with https://github.com/eic/EICrecon/pull/1605, this will be needed to keep the benchmark working.
No
No
=> tracking_performances: adapt to upcoming naming change for truth/real seeding collection names

Snakefile
=> Snakefile: set reties to 3 for fetch_epic

benchmarks/backgrounds/ecal_backwards.org, benchmarks/backwards_ecal/backwards_ecal.org, benchmarks/ecal_gaps/ecal_gaps.org
=> benchmarks/*: use xaxis.labellocation, yaxis.labellocation

benchmarks/zdc_lyso/analysis/analysis.py
Fix flakiness
```
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 800.
```
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3921285#L8566
=> zdc_lyso: set maxfev=10000 for curve_fit

benchmarks/femc_electron/Snakefile, benchmarks/femc_photon/Snakefile, benchmarks/femc_pi0/Snakefile
=> benchmarks/femc_*: scale event count with momentum

.gitlab-ci.yml, Snakefile, benchmarks/backwards_ecal/Snakefile
This metadata is to be used by the image_browser.
=> Initial implementation of metadata

benchmarks/ecal_gaps/Snakefile, benchmarks/ecal_gaps/config.yml
This should speed up the simulation a bit.
=> benchmarks/ecal_gaps: switch to epic_inner_detector configuration

Snakefile, benchmarks/backwards_ecal/Snakefile, benchmarks/ecal_gaps/Snakefile
Gradually enable additional Snakemake caching.
=> ecal_gaps: enable caching for simulation/reconstruction

benchmarks/backwards_ecal/Snakefile, benchmarks/backwards_ecal/backwards_ecal.org, benchmarks/backwards_ecal/config.yml, benchmarks/backwards_ecal/requirements.txt
=> backwards_ecal: run with dask

benchmarks/insert_muon/Snakefile, benchmarks/insert_neutron/Snakefile, benchmarks/insert_tau/Snakefile, benchmarks/zdc_lambda/Snakefile, benchmarks/zdc_lambda/analysis/gen_lambda_decay.cxx, benchmarks/zdc_lyso/Snakefile, benchmarks/zdc_neutron/config.yml, benchmarks/zdc_photon/Snakefile, benchmarks/zdc_pi0/Snakefile, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/Snakefile, benchmarks/zdc_sigma/analysis/gen_sigma_decay.cxx
Similar to #109 and others before.
=> zdc_*: enable caching

benchmarks/zdc_sigma/analysis/sigma_plots.py
Same as #124. Not clear to me what is going on.
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4506712
=> zdc_sigma: ignore failed fit (flaky)

benchmarks/backgrounds/requirements.txt, benchmarks/backwards_ecal/requirements.txt, benchmarks/lfhcal/Snakefile, benchmarks/tracking_performances/Snakefile, benchmarks/zdc_sigma/analysis/sigma_plots.py
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4529063#L370
=> lfhcal,tracking_performance: update to use 24.10.1 and 24.12.0

.gitlab-ci.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/Snakefile
Fixes zdc_sigma benchmark failures.
=> zdc_pi0: don't cleanup for zdc_sigma

.gitlab-ci.yml
Store artifacts also for failed pipelines.
=> feat: always store artifacts

benchmarks/zdc_lambda/analysis/lambda_plots.py, benchmarks/zdc_photon/analysis/zdc_photon_plots.py
#138 causes some regressions for running against the current stable version of EICrecon (1.22.0)
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4744073
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4744057
=> zdc_{lambda,photon}: disable parts that don't work for EICrecon 1.22

benchmarks/zdc_lambda/analysis/lambda_plots.py, benchmarks/zdc_photon/analysis/zdc_photon_plots.py
More issues that need to be addressed:
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4746551
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4746535
=> zdc_{lambda,photon}: fix logic, run more code conditionally

benchmarks/zdc_photon/analysis/zdc_photon_plots.py
Issues like
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5083018#L117
=> zdc_photon: pass failed fits

.gitlab-ci.yml
This PR removes the always-failing S3 setup.
No.
No.
=> fix(ci): don't mc config host add S3

benchmarks/backwards_ecal/backwards_ecal.org
=> backwards_ecal: extend E/p range to fix the fit

.gitlab-ci.yml, benchmarks/tracking_performances/Script_widebin.sh
`setup.sh` has been deprecated for a  while now.
No.
No.
=> fix: use bin/thisepic.sh instead of setup.sh

benchmarks/insert_neutron/analysis/neutron_plots.py
Fixes https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5735031#L184
perhaps we should review all scripts for this to have this fixed everywhere.
=> neutron_plots.py: set values to NAN in fit fail fallback

benchmarks/calo_pid/config.yml, benchmarks/zdc_lyso/config.yml
Stopgap to prevent #178 from blocking pull requests.
=> zdc_lyso: add allow_failure

benchmarks/beamline/Snakefile, benchmarks/femc_electron/Snakefile, benchmarks/femc_photon/Snakefile, benchmarks/femc_pi0/Snakefile, benchmarks/insert_muon/Snakefile, benchmarks/insert_neutron/Snakefile, benchmarks/insert_tau/Snakefile, benchmarks/zdc_lambda/Snakefile, benchmarks/zdc_lyso/Snakefile, benchmarks/zdc_neutron/Snakefile, benchmarks/zdc_photon/Snakefile, benchmarks/zdc_pi0/Snakefile, benchmarks/zdc_sigma/Snakefile
This should help to crack down on some of the spurious failures.
=> treewide: set ddsim simulation seed

benchmarks/calo_pid/config.yml
This is a partial revert of 4833ca67fd0921eae9d16f065ef149e990c6d715
=> calo_pid: allow_failure for bench job again

benchmarks/calo_pid/Snakefile, benchmarks/calo_pid/config.yml
=> calo_pid: enable caching for reco stage

benchmarks/insert_neutron/analysis/neutron_plots.py, benchmarks/insert_neutron/config.yml
This allows insert_neutron to fail.
No.
No.
=> fix: insert_neutron: allow_failure: true

benchmarks/femc_electron/analysis/femc_electron_plots.py, benchmarks/femc_electron/config.yml
This PR aims to avoid and debug issues like https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5924444#L129.
=> femc_electron: wrap curve_fit in try/except
