Snakefile, benchmarks/backgrounds/Snakefile, benchmarks/ecal_gaps/Snakefile
This is needed to facilitate running benchmarks where downloads may happen.
https://github.com/eic/epic/pull/588
fails in
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/2627824
This is similar to https://github.com/eic/physics_benchmarks/pull/5
=> Snakefile: add warmup job to avoid parallel gdml downloads

benchmarks/ecal_gaps/ecal_gaps.org, benchmarks/ecal_gaps/requirements.txt
Fix for failure
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/2899956#L369
```output
awkward.errors.FieldNotFoundError: no field 'MCParticles.momentum.x' in record with 7 fields
This error occurred while attempting to slice
<Array-typetracer [...] type='## * {EcalBarrelImagingRecHits: {"EcalBar...'>
with
'MCParticles.momentum.x'
```
=> Fix ecal_gaps benchmark

.gitlab-ci.yml
We can start triggering physics and detector pipelines in parallel. We don't need to test physics benchmarks for each test of detector benchmarks, as there is no actual dependency.
=> .gitlab-ci.yml: stop triggering physics and reconstruction downstream pipelines

benchmarks/tracking_performances/Script_widebin.sh, benchmarks/tracking_performances/Tracking_Performances.C, benchmarks/tracking_performances/doCompare_truth_real_widebins_mom.C, benchmarks/tracking_performances/readme.txt
- [x ] New feature (issue #__)
- [ x] Other: __
Maybe we can add a path for the geometry as configurable? I don't know the best way so after your suggestion, I will change the path for geometry in script_widebin.sh.
- [ x
] Changes have been communicated to collaborators
NO
No, This code can be used to extract the momentum resolution with the updated geometry and material map. The most affected quantity after the update of geometry is momentum resolution. It produces all the debug plots for truth/real seeding and final comparison plots for the momentum resolution with truth/real seeding attached. The number of events defaults are 10k but can be increased and can be optimized. I can further add a string on the file plot adding epic version.
=> Tracking benchmark

Snakefile, benchmarks/ecal_gaps/Snakefile, config.yaml
We are looking to migrate to Snakemake where remote store has a different incompatible syntax, and also broken. This PR brings repository into a state when that functionality is not relied up, so the transition can be done smoothly.
=> drop use of Snakemake 7.x-specific remote functionality

.gitlab-ci.yml, Snakefile, benchmarks/ecal_gaps/Snakefile, benchmarks/ecal_gaps/ecal_gaps.org, benchmarks/tracking_performances/Script_widebin.sh, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/Tracking_Performances.C, benchmarks/tracking_performances/config.yml
This enables tracking_performances as a benchmark running on eicweb. This also adds a Snakefile that can be used interactively. The simulations produced should match the blueprint of the official productions, so that the workflow can be extended to running over campaigns next.
=> benchmarks/tracking_performances: implement CI

benchmarks/tracking_performances/Snakefile
Fixes a regression from crossed merges of
https://github.com/eic/detector_benchmarks/pull/29
https://github.com/eic/detector_benchmarks/pull/30
=> tracking_performances: fix for removed 7.x-specific remote

benchmarks/tracking_performances/doCompare_truth_real_widebins_mom.C
Minor fix in the code and range on the X axis is modified.
- [ x] Other: __
- minor fix in the code
- [ x] Changes have been communicated to collaborators
No
No
=> tracking_performances: Adjust axis extent

.github/workflows/mirror.yaml
Currently, one has to manually remove branches on both repositories. This should take care of propagating the github deletions.
=> mirror.yaml: mirror branch delete actions to eicweb

benchmarks/ecal_gaps/Snakefile
A minor fix to allow using with non-standard DETECTOR_CONFIG.
=> ecal_gaps: use DETECTOR_CONFIG from the wildcard in eicrecon

.gitlab-ci.yml, benchmarks/tracking_performances/README.md, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/Tracking_Performances.C, benchmarks/tracking_performances/config.yml, benchmarks/tracking_performances/doCompare_truth_real_widebins_mom.C
This enables running over campaigns. The 15 GeV point had to be replaced with 20 GeV because that is what is currently available in the productions.
The current strategy is to run over a single file and enable caching of those to scratch on eicweb. We can expand once this is confirmed to be workable.
=> tracking_performance: enable running over campaigns

benchmarks/tracking_performances/config.yml
This PR causes bench:tracking_performance to run with 3 cores (simultaneous jobs). This should balance the pipeline better.
No.
No.
=> fix: bench:tracking_performance: `snakemake --cores 3`

benchmarks/tracking_performances/Snakefile
This uses `montage` tool from ImageMagick to combine individual plots into one to reduce number of files. The resulting plot is then placed to `results/` directory so that it can be uploaded.
=> tracking_performances: upload debug plots as artifacts

Snakefile, benchmarks/backgrounds/Snakefile, benchmarks/barrel_ecal/Snakefile, benchmarks/ecal_gaps/Snakefile, benchmarks/tracking_performances/Snakefile
Should help to avoid issues like jobs hanging until timeout [1] and processes keeping running after ctrl-c in the interactive running.
[1] https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3601180
=> treewide: use `set -m` and exec to avoid lingering ddsim processes

.gitlab-ci.yml, Snakefile, benchmarks/backgrounds/Snakefile, snakemake.yml
XRootD had been down for two weekends in a row. It's time to switch back to S3.
=> snakemake.yml: allow using S3 (XRootD is down sometimes)

benchmarks/ecal_gaps/Snakefile, benchmarks/tracking_performances/Snakefile
This is intended to advance forward the deprecation.
=> treewide: use podio:output_collections instead of deprecated podio:output_include_collections

.gitlab-ci.yml, Snakefile, benchmarks/backwards_ecal/Snakefile, benchmarks/backwards_ecal/backwards_ecal.org, benchmarks/backwards_ecal/config.yml, benchmarks/backwards_ecal/requirements.txt
Implements a benchmark for EEEMCal, currently showing just the pion rejection.
=> Add backwards_ecal benchmark

.gitlab-ci.yml, benchmarks/backgrounds/config.yml, benchmarks/backwards_ecal/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/tracking_performances/config.yml, benchmarks/zdc_lyso/config.yml
The failure path for now will not cleanup to allow for restarts. Ideally, the `collect:` jobs could do targeted cleanup using Snakemake.
=> .gitlab-ci.yml: cleanup disk space on success

benchmarks/backwards_ecal/Snakefile, benchmarks/ecal_gaps/Snakefile, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/config.yml
`bench:tracking_performance` is consistently redoing some simulations: https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3758782. The first change marks those as non-triggering (it may be not the issue, but could be that at least one of the protocols does not mirror the timestamps). The second should prevent needless simulation of 15 GeV and simulate 20 GeV that is actually used.
=> Avoid redoing simulations in `bench:tracking_performance`

.github/workflows/mirror.yaml
This provides faster feedback to github about the action taken to start the pipeline.
=> mirror.yaml: Set pending EICweb status

.gitlab-ci.yml, Snakefile, benchmarks/backgrounds/config.yml, benchmarks/backwards_ecal/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/tracking_performances/config.yml, benchmarks/zdc_lyso/config.yml
If #43 is indeed caused by wiped common files, we can't store those on /scratch, but we also would like to cache those downloads, if possible.
=> Cache fetch_epic using Snakemake's caching facility

.gitlab-ci.yml
We are looking to integrate eicweb with image_browser. Writing results to XRootD may be a good way to provide them to the service.
`allow_failure` is enabled to allow some tolerance for tokens that will be expiring.
=> .gitlab-ci.yml: deploy results to XRootD

.github/workflows/mirror.yaml
Looks like we lost some PR due to cancellation
https://github.com/eic/detector_benchmarks/actions/runs/10968859151
It might be that merges are conflicting with themselves or with delete.
=> mirror.yaml: add github.event_name to concurrency::group

.gitlab-ci.yml, benchmarks/insert_muon/config.yml, benchmarks/zdc_photon/config.yml, benchmarks/zdc_pi0/config.yml
The change https://github.com/eic/epic/pull/713 in how the epic geometry is tested allows to remove some extra logic from benchmarks.
=> .gitlab-ci.yml: don't build detector

Snakefile
This fixes a major bug, which causes all fetch_epic outputs to be cached under the same name.
=> Snakefile: fix caching in fetch_epic

benchmarks/femc_electron/config.yml, benchmarks/femc_photon/config.yml, benchmarks/femc_pi0/config.yml, benchmarks/insert_muon/config.yml, benchmarks/insert_neutron/config.yml, benchmarks/zdc_lambda/config.yml, benchmarks/zdc_photon/config.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/config.yml
This is needed for cleanup to work (.det_benchark symlinks sim_outputs to scratch). We have been overfilling scratch and femc benchmarks produce largest edm4hep files (HitContributions at 80GeV).
=> **/config.yml: collect_results shoud extend from .det_benchmark

.pre-commit-config.yaml, benchmarks/zdc_photon/config.yml
Originally, pre-commit-ci enabled for #86, which is not ready. Let's add some configuration for now.
=> Add a basic .pre-commit-config.yaml

.gitlab-ci.yml, benchmarks/backgrounds/config.yml, benchmarks/backwards_ecal/config.yml, benchmarks/barrel_ecal/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/femc_electron/config.yml, benchmarks/femc_photon/config.yml, benchmarks/femc_pi0/config.yml, benchmarks/insert_muon/config.yml, benchmarks/insert_neutron/config.yml, benchmarks/lfhcal/config.yml, benchmarks/material_scan/config.yml, benchmarks/tracking_performances/config.yml, benchmarks/tracking_performances_dis/config.yml, benchmarks/zdc_lambda/config.yml, benchmarks/zdc_lyso/config.yml, benchmarks/zdc_photon/config.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/config.yml
This changes all workflows to ignore mtime. In principle, we shouldn't need re-run anything ever on CI – all that is produced is produced anew except what's cached.
The issue reported in https://github.com/eic/epic/pull/796#issuecomment-2422950589
happens specifically in bench:backwards_ecal, because it's the only workflow with caching. My hypothesis is that several parallel simm:backwards_ecals may overwrite edm4hep files in the cache twice with different mtimes, then in bench step the reconstructed edm4eic may appear to be out of date with respect to the latest mtime in cache. That causes reconstruction to be re-ran in a single bench job and cause a time out. If we can just ignore mtime, that should stop being a problem.
This also applies --cache globally, which should be harmless.
=> .gitlab-ci.yml: introduce global SNAKEMAKE_FLAGS, don't re-run based on mtime

.gitlab-ci.yml, benchmarks/backwards_ecal/Snakefile
A follow up on #92 (partially reverts).
cc https://github.com/eic/epic/pull/796#issuecomment-2422950589
=> backwards_ecal: enable caching for the reco step

benchmarks/femc_electron/analysis/femc_electron_plots.py, benchmarks/femc_photon/analysis/femc_photon_plots.py, benchmarks/femc_pi0/analysis/femc_pi0_plots.py, benchmarks/insert_muon/analysis/muon_plots.py, benchmarks/insert_neutron/analysis/neutron_plots.py, benchmarks/zdc_lambda/analysis/lambda_plots.py, benchmarks/zdc_photon/analysis/zdc_photon_plots.py, benchmarks/zdc_pi0/analysis/zdc_pi0_plots.py
=> treewide: use maxfev=10000

.gitlab-ci.yml
This is needed to have those uploaded to the image_browser.
=> .gitlab-ci.yml: add lfhcal to deploy_results

benchmarks/tracking_performances_dis/README.md, benchmarks/tracking_performances_dis/Snakefile, benchmarks/tracking_performances_dis/analysis/vtx_dis_analysis.cxx, benchmarks/tracking_performances_dis/analysis/vtx_dis_plots.cxx, benchmarks/tracking_performances_dis/config.yml
This adds a vertexing benchmark for Deep Inelastic Scattering (DIS) events.
No.
Yes. This adds a new benchmark.
=> Added benchmark for vertexing studies in DIS events

benchmarks/lfhcal/Snakefile
Similar to #88 and others
cc @steinber
=> lfhcal: scale event count with momentum

benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/doCompare_truth_real_widebins_dcaT.C, benchmarks/tracking_performances/doCompare_truth_real_widebins_dcaz.C
There is a further addition of tracking performance plots e.g. DCAT and DCAz. The code was tested for local rules and works fine. Since DCAT and DCAz distributions are the functions of transverse momentum, we need to use large statistics (in my case I used 50k events).  
- [ x] Tests for the changes have been added
No
No
=> Adding resolutions of DCAT and DCAz to the benchmark

benchmarks/tracking_performances/Snakefile
Fix failures like https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4261645#L440
=> tracking_performances: fix a race condition (several instances of a job uses same file)

benchmarks/backwards_ecal/Snakefile, benchmarks/calo_pid/Snakefile, benchmarks/ecal_gaps/Snakefile, benchmarks/lfhcal/Snakefile, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances_dis/Snakefile, benchmarks/zdc_lyso/Snakefile
Recent versions of Snakemake are stricter about tab/space mixing and are more eager to show syntax warnings. This addresses the issues that will pop up.
=> Syntax fixes

benchmarks/backwards_ecal/Snakefile, benchmarks/backwards_ecal/backwards_ecal.org, benchmarks/backwards_ecal/config.yml
This allows to process the official 24.10.1 campaign, as prescribed for PDR. There are two ways: download a 350 Gb full dataset, or try to stream the relevant columns from XRootD.
Other changes include removal of all hit summation method (for clarity) and other visual tweaks.
=> backwards_ecal: changes for the PDR

benchmarks/calo_pid/Snakefile, benchmarks/calo_pid/calo_pid.org
This allows analyzing larger datasets and potentially implementing campaign processing. Some other minor tweaks are included.
=> calo_pid: pass input files via a list file

benchmarks/ecal_gaps/requirements.txt
This is in response to recent regressions in dask_awkward caused by changes in new dask releases.
=> ecal_gaps: pin everything in requirements.txt

benchmarks/backwards_ecal/Snakefile, benchmarks/backwards_ecal/backwards_ecal.org, benchmarks/backwards_ecal/config.yml, benchmarks/backwards_ecal/requirements.txt
This rewrites parts of the benchmark using dask, enabling multithreaded streaming with lazy column selection. This allows to get through a 24.10.1 campaign in about about 6 minutes at 16 threads. On eicweb with 5 threads it takes about 25 minutes. A downside of this is that dask is a bit harder to use (e.g. with existing ML tools).
=> backwards_ecal: run with dask

benchmarks/insert_neutron/analysis/neutron_plots.py
This should help us to avoid spurious failures like
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4468327#L131
=> insert_neutron: ignore failed fit (flaky)

benchmarks/tracking_performances_dis/config.yml
This is needed to produce clearer plot names in image_viewer https://eic.jlab.org/epic/image_browser.html#
Ideally we don't just number those, but give them readable names.
This also avoids the naming confusion between tracking and vertexing.
=> {tracking,vertexing}_performances_dis: name png files after benchmark

benchmarks/backwards_ecal/backwards_ecal.org
This avoids https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4661855#L5496.
FYI, https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
=> fix: avoid warning in backwards_ecal with fr-string

benchmarks/backwards_ecal/backwards_ecal.org
Should help to understand issues like https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4662959#L5504
=> backwards_ecal: provide more verbose output for fit fail

benchmarks/zdc_lambda/Snakefile, benchmarks/zdc_lambda/analysis/lambda_plots.py, benchmarks/zdc_neutron/Snakefile, benchmarks/zdc_neutron/analysis/fwd_neutrons_recon.C, benchmarks/zdc_photon/Snakefile, benchmarks/zdc_photon/analysis/zdc_photon_plots.py
Makes the benchmarks for the ZDC lambdas, photons, and neutrons use the reconstructed particles from EICrecon (see https://github.com/eic/EICrecon/pull/1731 ), rather than reconstructing them in the analysis code of the benchmarks.
No
Yes.
=> ZDC benchmarks use reconstructed particles from EICrecon, rather than attempting to reconstruct them directly

Snakefile, benchmarks/backgrounds/Snakefile, benchmarks/backwards_ecal/Snakefile, benchmarks/tracking_performances_dis/Snakefile
Replace /work/eic2 with /volatile/eic in executable code. Docs to follow. To be merged after EVGEN has been migrated (note: backwards_ecal also uses RECO).
No.
No.
=> fix: /work/eic2 -> /volatile/eic

benchmarks/timing/run_timing.sh
This avoids spurious success as in https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/4837441
No
No
=> fix: sim:timing: fail job when fail ddsim

.github/workflows/mirror.yaml, .gitlab-ci.yml
Since GITHUB_PR and others are passed from eic_container to detector_benchmarks and others, we observe 3 additional statuses:
But in reality there should be 6 for stable and nightly. This introduces pipeline tag into the job name. Description is truncated to remove some redundant messages that are already conveyed via status icon and GitHub UI.
=> .gitlab-ci.yml: ommit redundant description in github status, report BENCHMARKS_TAG instead

benchmarks/tracking_performances/config.yml
Noticed the artifacts are empty, only 24.10.1 is available. This will fix that.
=> tracking_performance: preserve result/ for tracking_performance_local

benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances_dis/Snakefile
This is the last benchmark that is missing caching. Should be similar to all previous cases.
=> tracking_performances{,_dis}: add simulation caching

benchmarks/backwards_ecal/config.yml, benchmarks/calo_pid/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/femc_electron/config.yml, benchmarks/femc_photon/config.yml, benchmarks/femc_pi0/config.yml, benchmarks/insert_muon/config.yml, benchmarks/insert_neutron/config.yml, benchmarks/insert_tau/config.yml, benchmarks/lfhcal/config.yml, benchmarks/zdc_lambda/config.yml, benchmarks/zdc_lyso/config.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/config.yml
This PR adds `when: always` to all `collect` jobs that only run the standard content with `snakemake --delete-output-files`.
No.
No.
=> feat: always run collect jobs

.gitlab-ci.yml
This PR ensures that the status jobs won't be attempted when they are going to fail anyway.
No.
No.
=> fix(ci):  don't run status jobs when GITHUB_SHA undefined

benchmarks/tracking_performances/NhitsvsEta_ePIC.C, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances/Tracking_Performances.C, benchmarks/tracking_performances/config.yml, benchmarks/tracking_performances/draw_hits.C
This pull request includes the code that will run the simulation output EDM file at a given momentum and produce the hitmap XY and RZ for the ePIC tracker. Additional code generates the average Nhits vs Eta distribution for the ePIC tracker. 
- [x ] Other: __
This will directly allow us to see the changes in the geometry as well as the average number of hits vs eta.
- [x ] Changes have been communicated to collaborators
- The expected output is also attached with the ePIC 24.12.0, which I will present in the next tracking meeting.
- In the hit map (RZ), it can be seen inner MPGD geometry is changed as well as the inner radius of forward MPGD disks, ETOF is increased.
No
No
=> Adding Hitmap and Average Nhits vs Eta map

benchmarks/lfhcal/LFHCAL_Performance.C, benchmarks/zdc_neutron/analysis/fwd_neutrons_geant.C, benchmarks/zdc_neutron/analysis/fwd_neutrons_recon.C
This is an issue with running benchmarks with after EDM4hep update (happened long time ago, actually).
```
Error in <TTreeReaderArrayBase::CreateContentProxy()>: The branch MCParticles.momentum.x contains data of type double. It cannot be accessed by a TTreeReaderArray<float>
Error in <TTreeReaderArrayBase::CreateContentProxy()>: The branch MCParticles.momentum.y contains data of type double. It cannot be accessed by a TTreeReaderArray<float>
Error in <TTreeReaderArrayBase::CreateContentProxy()>: The branch MCParticles.momentum.z contains data of type double. It cannot be accessed by a TTreeReaderArray<float>
```
lfhcal: https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5766771/raw
zdc_neutron: https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5766779 …
=> lfhcal,zdc_neutron: MCParticles.momentum is now double, not float

benchmarks/backgrounds/Snakefile, benchmarks/backwards_ecal/Snakefile, benchmarks/calo_pid/Snakefile, benchmarks/ecal_gaps/Snakefile, benchmarks/femc_electron/Snakefile, benchmarks/femc_photon/Snakefile, benchmarks/femc_pi0/Snakefile, benchmarks/insert_muon/Snakefile, benchmarks/insert_neutron/Snakefile, benchmarks/insert_tau/Snakefile, benchmarks/lfhcal/Snakefile, benchmarks/nhcal_acceptance/Snakefile, benchmarks/nhcal_basic_distribution/Snakefile, benchmarks/tracking_performances/Snakefile, benchmarks/tracking_performances_dis/Snakefile, benchmarks/zdc_lambda/Snakefile, benchmarks/zdc_lyso/Snakefile, benchmarks/zdc_neutron/Snakefile, benchmarks/zdc_photon/Snakefile, benchmarks/zdc_pi0/Snakefile, benchmarks/zdc_sigma/Snakefile
I see unnecessary simulation re-ran due to updated warmup. E.g. job https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5844320 starts with
```output
[Sun Jul  6 13:53:47 2025]
localrule org2py:
input: /builds/EIC/benchmarks/detector_benchmarks/benchmarks/calo_pid/calo_pid.org, /builds/EIC/benchmarks/detector_benchmarks/benchmarks/common/org2py.awk (cached)
output: benchmarks/calo_pid/calo_pid.py
jobid: 405
reason: Missing output files: benchmarks/calo_pid/calo_pid.py
wildcards: NOTEBOOK=benchmarks/calo_pid/calo_pid
resources: tmpdir=/tmp
[Sun Jul  6 13:53:47 2025]
Finished job 405.
1 of 406 steps (0.2%) done
Select jobs to execute...
Execute 1 jobs...
[Sun Jul  6 13:53:47 2025]
Job 4: Ensuring that calibrations/fieldmaps are available for epic_inner_detector
Reason: …
```
=> treewide: mark warmup as ancient

benchmarks/backgrounds/config.yml, benchmarks/backwards_ecal/config.yml, benchmarks/beamline/config.yml, benchmarks/calo_pid/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/insert_muon/config.yml, benchmarks/insert_neutron/config.yml, benchmarks/insert_tau/config.yml, benchmarks/lfhcal/config.yml, benchmarks/nhcal_acceptance/config.yml, benchmarks/nhcal_basic_distribution/config.yml, benchmarks/tracking_performances/config.yml, benchmarks/tracking_performances_dis/config.yml, benchmarks/zdc_lambda/config.yml, benchmarks/zdc_neutron/config.yml, benchmarks/zdc_photon/config.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/config.yml
Resolves #159. I have not found a way to query CI runner cores, we could probably poke into cgroups, but lets check this first.
=> treewide: switch to cores 1 in each job

benchmarks/backgrounds/config.yml, benchmarks/backwards_ecal/config.yml, benchmarks/beamline/config.yml, benchmarks/calo_pid/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/insert_muon/config.yml, benchmarks/insert_neutron/config.yml, benchmarks/insert_tau/config.yml, benchmarks/lfhcal/config.yml, benchmarks/nhcal_acceptance/config.yml, benchmarks/nhcal_basic_distribution/config.yml, benchmarks/tracking_performances/config.yml, benchmarks/tracking_performances_dis/config.yml, benchmarks/zdc_lambda/config.yml, benchmarks/zdc_neutron/config.yml, benchmarks/zdc_photon/config.yml, benchmarks/zdc_pi0/config.yml, benchmarks/zdc_sigma/config.yml
We now get job timeouts. Probably should go back to oversubscribing.
=> treewide: revert from using 1 core to newly defined $MAX_CORES_PER_JOB

benchmarks/beamline/Snakefile
Mysterious failures in https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/5975884#L234 must be somehow related to calibrations loading.
=> beamline: analyses load geometry, so they have to depend on warmup

benchmarks/backwards_ecal/config.yml, benchmarks/ecal_gaps/config.yml, benchmarks/nhcal_basic_distribution/config.yml, benchmarks/tracking_performances_dis/config.yml
Looks like some relatively recent changes pushed these benchmarks over the timeout.
=> backwards_ecal,ecal_gaps,tracking_performances_dis,nhcal_basic_distribution_full: increase timeouts
